import { NgModule, ModuleWithProviders } from '@angular/core';
import { CommonModule } from '@angular/common';
import {
  NbUserModule,
  NbThemeModule,
  NbLayoutModule,
  NbSidebarModule,
  NbMenuModule,
  NbActionsModule,
  NbCardModule,
  NbSearchModule,
  NbContextMenuModule,
  NbIconModule,
  NbSelectModule,
  NbButtonModule,
  NbWindowModule,
  NbInputModule,
  NbAlertModule,
  NbSpinnerModule,
  NbToastrModule,
  NbDialogModule,
  NbDatepickerModule,
  NbCheckboxModule,
  NbListModule,
  NbStepperModule,
  NbTabsetModule,
  NbAccordionModule,
  NbFormFieldModule,
  NbRouteTabsetModule,
} from '@nebular/theme';
import { NbEvaIconsModule } from '@nebular/eva-icons';

@NgModule({
  declarations: [],
  imports: [
    NbRouteTabsetModule,
    NbFormFieldModule,
    NbCardModule,
    NbActionsModule,
    NbSearchModule,
    NbUserModule,
    NbContextMenuModule,
    NbIconModule,
    NbSelectModule,
    NbButtonModule,
    NbInputModule,
    NbAlertModule,
    NbSpinnerModule,
    NbLayoutModule,
    NbEvaIconsModule,
    NbCheckboxModule,
    NbListModule,
    NbThemeModule,
    NbSidebarModule,
    NbMenuModule,
    NbWindowModule,
    NbToastrModule,
    NbDialogModule,
    NbDatepickerModule,
    NbStepperModule,
    NbTabsetModule,

    CommonModule,
  ],
  exports: [
    NbRouteTabsetModule,
    NbFormFieldModule,
    NbCardModule,
    NbActionsModule,
    NbSearchModule,
    NbUserModule,
    NbContextMenuModule,
    NbIconModule,
    NbSelectModule,
    NbButtonModule,
    NbInputModule,
    NbAlertModule,
    NbSpinnerModule,
    NbLayoutModule,
    NbEvaIconsModule,
    NbCheckboxModule,
    NbListModule,
    NbThemeModule,
    NbSidebarModule,
    NbMenuModule,
    NbWindowModule,
    NbToastrModule,
    NbDialogModule,
    NbDatepickerModule,
    NbStepperModule,
    NbTabsetModule,
    NbAccordionModule,

    CommonModule,
  ],
})
export class NebularImportsModule { }
